services:
  app:
    container_name: medicine-bank-backend-app
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${DB_CONTAINER_NAME}
        POSTGRES_PORT: ${POSTGRES_PORT}
        PORT: ${PORT}
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres

    stdin_open: true
    tty: true

  postgres:
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}

    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - medicine_bank_dev_db:/var/lib/postgresql/data

volumes:
  medicine_bank_dev_db:
